export const USER = 'USER';             //用户
export const REGISTER = 'REGISTER';     //注册
export const LOGIN = 'LOGIN';           //登录
export const LOGOUT = 'LOGOUT';         //退出登录
export const USER_MODIFY = 'USER_MODIFY'; //修改用户信息
export const USER_INFO = 'USER_INFO';     //获取用户信息
export const AX_READ_LIST = 'AX_READ_LIST';
export const AX_READ_LIST_USER = 'AX_READ_LIST_USER';
export const AX_READ_ADD = 'AX_READ_ADD';
export const AX = 'AX';
export const AX_USER = 'AX_USER';
export const AX_COMMUNITY = 'AX_COMMUNITY';
export const AX_LIST = 'AX_LIST';
export const AX_USER_ADD = 'AX_USER_ADD';
export const AX_SEARCH = 'AX_SEARCH';
export const PRAISE = 'PRAISE';                  //点赞
export const IS_PRAISE = 'IS_PRAISE';            //是否点赞
export const PRAISE_REMOVE = 'PRAISE_REMOVE';    //取消点赞
export const COMMENT = 'COMMENT';                //评论详情
export const COMMENT_LIST = 'COMMENT_LIST';      //评论列表
export const COMMENT_ADD = 'COMMENT_ADD';        //添加评论
export const COMMENT_REMOVE = 'COMMENT_REMOVE';  //删除评论
export const FOLLOWS = 'FOLLOWS';                //关注
export const IS_FOLLOWED = 'IS_FOLLOWED';        //是否关注
export const FOLLOWS_REMOVE = 'FOLLOWS_REMOVE';  //取消关注
export const FOLLOWS_LIST = 'FOLLOWS_LIST';      //关注用户列表
export const COLLECT = 'COLLECT';                //收藏
export const IS_COLLECT = 'IS_COLLECT';          //是否收藏
export const COLLECT_REMOVE = 'COLLECT_REMOVE';  //取消收藏
export const COLLECT_LIST = 'COLLECT_LIST';      //收藏列表
export const CATE_LIST = 'CATE_LIST';  		     //分类
export const COMMUNITY_LIST = 'COMMUNITY_LIST';  //社区

